title: Dawoon Leem
description: My Personal Blog
author: Dawoon Leem
logo: /static/img/avatar.jpg
github: https://github.com/LeemDawoon
about: developer

baseurl: ""
url: ""

allowsearch: true

#disqus_shortname: aboutashu
google_analytics: UA-100776614-1

#share:
#  twitter_username: \#
#  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
